modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="jarviscraftingcore"
version="1.0.0"
displayName="JARVIS Crafting Core"
description='''
A futuristic, sentient crafting block.'''

[[dependencies.jarviscraftingcore]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jarviscraftingcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
